# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aegis < Formula
  desc ""
  homepage "https://github.com/lucasloureiror/AegisPass"
  version "2.1.0"

  on_macos do
    on_intel do
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v2.1.0/AegisPass_Darwin_x86_64.tar.gz"
      sha256 "b4015a0faa4d28abeb8209db3b593f2e15c305f1eda16a2ed0ef271ba79aca77"

      def install
        bin.install "aegis"
      end
    end
    on_arm do
      url "https://github.com/lucasloureiror/AegisPass/releases/download/v2.1.0/AegisPass_Darwin_arm64.tar.gz"
      sha256 "666350b5d476a4144fac280d8c9341acd9c077d6441378b8bec4902cf3e74db4"

      def install
        bin.install "aegis"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucasloureiror/AegisPass/releases/download/v2.1.0/AegisPass_Linux_x86_64.tar.gz"
        sha256 "fb86ecff1133a20316b064703c4d652ad71804ff63c438becefaf9ad546a8bfb"

        def install
          bin.install "aegis"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucasloureiror/AegisPass/releases/download/v2.1.0/AegisPass_Linux_arm64.tar.gz"
        sha256 "d0191659ba637e1012d8e05ec1b278fa104e2219f9dc5d2e507274abcc1b879b"

        def install
          bin.install "aegis"
        end
      end
    end
  end
end
